name: table_calendar_hijri
description: Highly customizable, feature-packed calendar widget for Flutter, now with Hijri.
version: 4.0.0
homepage: https://github.com/kazelectronics/table_calendar_hijri

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  simple_gesture_detector: ^0.2.0
  quiver:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
